# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc2457b2a685407c5ff9aec549174bc0a63f22e04323f74eaf4ec4c5b740c4b23a23ed6d45cf47a406a6d01b5eece55f8aeb3cdef3c9f5d3dafcc772996c44e7

test:
  secret_key_base: 1b57af3e89dfcbba5ad015549c48d39c48015b16244a274de596c291e4b11984974fe4f546dfeec089d7b295fac96381ac2773cc1c81ae8360b4bed20928f041

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
